[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'vim-scripts/IndentAnything'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/tabpagebuffer.vim'

[[plugins]]
repo = 'vim-scripts/nginx.vim'

[[plugins]]
repo = 'chase/vim-ansible-yaml'

[[plugins]]
repo = 'tyru/operator-html-escape.vim'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'w0ng/vim-hybrid'

# [[plugins]]
# repo = 'jason0x43/vim-js-indent'

[[plugins]]
repo = 'thinca/vim-openbuf'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 't9md/vim-textmanip'

[[plugins]]
repo = 'qbbr/vim-twig'
