if !1 | finish | endif

set runtimepath+=~/.vim/

if has('vim_starting')
  if &compatible
    set nocompatible
  endif

  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))
  NeoBundleFetch 'Shougo/neobundle.vim'
  runtime! bundle.d/*.vim
call neobundle#end()

filetype plugin indent on

NeoBundleCheck

set bs=indent,eol,start
set title

runtime! conf.d/*.vim

