if &compatible
   set nocompatible
endif

set runtimepath^=~/.cache/dein/repos/github.com/Shougo/dein.vim/

let s:dein_path = expand('~/.cache/dein')
let s:toml_path = '~/.vim/dein.toml'
let s:toml_lazy_path = '~/.vim/deinlazy.toml'

if dein#load_state(s:dein_path)
  call dein#begin(s:dein_path)

  if dein#load_cache([expand('<sfile>'), s:toml_path, s:toml_lazy_path])
    call dein#load_toml(s:toml_path, {'lazy': 0})
    call dein#load_toml(s:toml_lazy_path, {'lazy' : 1})

    call dein#save_cache()
  endif

  call dein#end()
  call dein#save_state()
endif

if dein#check_install(['vimproc.vim'])
  call dein#install(['vimproc.vim'])
endif

if dein#check_install()
  call dein#install()
endif

filetype plugin indent on

runtime! bundle-conf.d/*.vim
runtime! conf.d/*.vim

